name: CI Develop Pipeline
on: 
  pull_request:
    types: [opened, closed, synchronize]
    branches:
     - 'develop'
jobs:
  code_check:
    if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
    
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create Local Properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' >> ./local.properties

      - name: build detekt
        run: ./gradlew detekt

      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893
        with:
              reviewdog_version: v1.3.2

      - name: Run reviewdog
        env:
              REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./app/build/reports/detekt/detekt.xml
              | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="error" -fail_on_error="true"

  on_pr_merge_success:
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feature/')}}
    runs-on: ubuntu-latest
    steps:
      - name: Login Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract issue key from branch naming
        run: echo "ISSUE_KEY=${GITHUB_HEAD_REF#feature/}" >> $GITHUB_ENV
        env:
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}

      - name: Close Jira issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          transition: 완료
